#COLORS
GREEN="\[\033[0;32m\]"
CYAN="\[\033[0;36m\]"
RED="\[\033[0;31m\]"
PURPLE="\[\033[0;35m\]"
BROWN="\[\033[0;33m\]"
CYAN="\[\033[0;36m\]"
LIGHT_GRAY="\[\033[0;37m\]"
LIGHT_BLUE="\[\033[1;34m\]"
LIGHT_GREEN="\[\033[1;32m\]"
LIGHT_CYAN="\[\033[1;36m\]"
LIGHT_RED="\[\033[1;31m\]"
LIGHT_PURPLE="\[\033[1;35m\]"
YELLOW="\[\033[1;33m\]"
WHITE="\[\033[1;37m\]"
RESTORE="\[\033[0m\]"

BOLD="\[\033[1m\["

#0 - Normal Style
# 1 - Bold
# 2 - Dim
# 3 - Italic
# 4 - Underlined
# 5 - Blinking
# 7 - Reverse
# 8 - Invisible

# Git prompt Settings
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM="verbose git"
GIT_PS1_SHOWCOLORHINTS=true


#git Prompt:
#from git-prompt docs:
#        Alternatively, for a slightly faster prompt, __git_ps1 can
#        be used for PROMPT_COMMAND in Bash or for precmd() in Zsh
#        with two parameters, <pre> and <post>, which are strings
#        you would put in $PS1 before and after the status string
#        generated by the git-prompt machinery.  e.g.
#        Bash: PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'
#          will show username, at-sign, host, colon, cwd, then
#          various status string, followed by dollar and SP, as
#          your prompt.

#helpful links
#https://ss64.com/bash/syntax-prompt.html
#https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
#https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/
#


PROMPT_DATETIME="$CYAN\D{%a %d %b} \t$RESTORE"
PROMPT_LAST_COMMAND="\$\?=$?"
PROMPT_HOST_AND_WD="$PURPLE\H: \w$RESTORE"
PROMPT_USERNAME="$PURPLE\u$RESTORE"
PROMPT_PROMPT="$BROWN!\! $CYAN\$ $RESTORE"

# export PROMPT_COMMAND="status=${?} __git_ps1 '\n$PROMPT_DATETIME  ${RED}status=$status$RESET \n$PROMPT_HOST_AND_WD\n$PROMPT_USERNAME' ' $PROMPT_PROMPT'"

function _prompt_command {
    local status=${?}
    STATUS_COLOR=$GREEN
    if [ ! $status -eq 0 ]; then STATUS_COLOR=$RED; fi
    __git_ps1 "\n$PROMPT_DATETIME  $BOLD|$RESTORE  ${STATUS_COLOR}exit_code=$status$RESET \n$PROMPT_HOST_AND_WD\n$PROMPT_USERNAME "  " $BROWN!\! $CYAN\$ $RESTORE"

}


export PROMPT_COMMAND=_prompt_command
export PROMPT_COMMAND+=' && echo -ne "\033]0;${PWD##*/}\007"' #TAB NAME location in Terminal

# export PS1="\n\[\e[0;36m\]\D{%a %d %b} \A\n\[\e[0;35m\]\H: \w\n\[\e[0;35m\]\u !\!__\[\e[0;36m\]\$ \[\e[m\]"

# export PROMPT_COMMAND="__git_ps1 \"$PRE_GIT_PROMPT\" \"$POST_GIT_PROMPT\""